In [10]:
import pandas as pd
df = pd.read_csv("disney-characters.csv")
df

,movie_title,release_date,hero,villian,song
0,\nSnow White and the Seven Dwarfs,"December 21, 1937",Snow White,Evil Queen,Some Day My Prince Will Come
1,\nPinocchio,"February 7, 1940",Pinocchio,Stromboli,When You Wish upon a Star
2,\nFantasia,"November 13, 1940",NaN,Chernabog,NaN
3,Dumbo,"October 23, 1941",Dumbo,Ringmaster,Baby Mine
4,\nBambi,"August 13, 1942",Bambi,Hunter,Love Is a Song
5,\nSaludos Amigos,"February 6, 1943",Donald Duck,NaN,Saludos Amigos\n
6,The Three Caballeros,"February 3, 1945",Donald Duck,NaN,NaN
7,\nMake Mine Music,"April 20, 1946",NaN,NaN,NaN
8,\nFun and Fancy Free,"September 27, 1947",Mickey Mouse,Willie the Giant,NaN
9,\nMelody Time,"May 27, 1948",NaN,NaN,Little Toot
10,\nThe Adventures of Ichabod and Mr. Toad,"October 5, 1949",Mr. Toad and Ichabod Crane,Mr. Winkie and The Headless Horseman,The Merrily Song
11,Cinderella,"February 15, 1950",Cinderella,Lady Tremaine,Bibbidi-Bobbidi-Boo
12,\nAlice in Wonderland,"July 28, 1951",Alice,Queen of Hearts,The Unbirthday Song
13,\nPeter Pan,"February 5, 1953",Peter Pan,Captain Hook,You Can Fly!
14,\nLady and the Tramp,"June 22, 1955",Lady and Tramp,Si and Am,Bella Notte
15,Sleeping Beauty,"January 29, 1959",Aurora,Maleficent,Once Upon a Dream
16,\nOne Hundred and One Dalmatians,"January 25, 1961",Pongo,Cruella de Vil,Cruella De Vil
17,\nThe Sword in the Stone,"December 25, 1963",Arthur,Madam Mim,Higitus Figitus\n
18,The Jungle Book,"October 18, 1967",Mowgli,Kaa and Shere Khan,The Bare Necessities\n
19,The Aristocats,"December 24, 1970",Thomas and Duchess,Edgar Balthazar,Ev'rybody Wants to Be a Cat
20,\nRobin Hood,"November 8, 1973",Robin Hood,Prince John,Oo De Lally
21,\nThe Many Adventures of Winnie the Pooh,"March 11, 1977",Winnie the Pooh,NaN,Winnie the Pooh
22,\nThe Rescuers,"June 22, 1977",Bernard and Miss Bianca,Madame Medusa,The Journey
23,\nThe Fox and the Hound,"July 10, 1981",Tod and Copper,Amos Slade,Best of Friends
24,\nThe Black Cauldron,"July 24, 1985",Taran,Horned King,NaN
25,\nThe Great Mouse Detective,"July 2, 1986",Basil,Professor Ratigan,The World's Greatest Criminal Mind
26,\nOliver & Company,"November 18, 1988",Oliver,Sykes,Once Upon a Time in New York City
27,The Little Mermaid,"November 17, 1989",Ariel,Ursula,Under the Sea
28,\nThe Rescuers Down Under,"November 16, 1990",Bernard and Miss Bianca,Percival C. McLeach,\n
29,Beauty and the Beast,"November 22, 1991",Belle,Gaston,Be Our Guest
30,\nAladdin,"November 25, 1992",Aladdin,Jafar,A Whole New World
31,\nThe Lion King,"June 24, 1994",Simba,Scar,Circle of Life
32,Pocahontas,"June 23, 1995",Pocahontas,Governor Ratcliffe,Colors of the Wind
33,\nThe Hunchback of Notre Dame,"June 21, 1996",Quasimodo,Claude Frollo,God Help the Outcasts
34,\nHercules,"June 27, 1997",Hercules,Hades,Go the Distance
35,\nMulan,"June 19, 1998",Mulan,Shan Yu,I'll Make a Man Out of You\n
36,Tarzan,"June 18, 1999",Tarzan,Clayton,You'll Be in My Heart
37,\nFantasia 2000,"December 17, 1999",NaN,NaN,NaN
38,\nDinosaur,"May 19, 2000",Aladar,Kron,NaN
39,\nThe Emperor's New Groove,"December 15, 2000",Kuzco,Yzma,My Funny Friend and Me\n
40,Atlantis: The Lost Empire,"June 15, 2001",Milo Thatch,Commander Rourke,Where the Dream Takes You
41,\nLilo & Stitch,"June 21, 2002",Lilo and Stitch,NaN,He Mele No Lilo\n
42,Treasure Planet,"November 27, 2002",Jim Hawkins,John Silver,I'm Still Here\n
43,Brother Bear,"November 1, 2003",Kenai,Denahi,Look Through My Eyes
44,\nHome on the Range,"April 2, 2004",Maggie,Alameda Slim,NaN
45,\nChicken Little,"November 4, 2005",Ace Cluck,Foxy Loxy,NaN
46,\nMeet the Robinsons,"March 30, 2007",Lewis,Doris,Little Wonders
47,\nBolt,"November 21, 2008",Bolt,Dr. Calico,I Thought I Lost You
48,\nThe Princess and the Frog,"December 11, 2009",Tiana,Dr. Facilier,Almost There
49,\nTangled,"November 24, 2010",Rapunzel,Mother Gothel,I See the Light
50,\nWinnie the Pooh,"July 15, 2011",Winnie the Pooh,NaN,Winnie the Pooh\n
51,Wreck-It Ralph,"November 2, 2012",Ralph,Turbo,Sugar Rush
52,\nFrozen,"November 27, 2013",Elsa,Prince Hans,Let It Go\n
53,Big Hero 6,"November 7, 2014",Hiro Hamada,Professor Callaghan,Immortals
54,\nZootopia,"March 4, 2016",Judy Hopps,NaN,Try Everything
55,\nMoana,"November 23, 2016",Moana,NaN,How Far I'll Go\n

In [11]:
df["movie_title"]=df["movie_title"].str.replace("\n","")
df

,movie_title,release_date,hero,villian,song
0,Snow White and the Seven Dwarfs,"December 21, 1937",Snow White,Evil Queen,Some Day My Prince Will Come
1,Pinocchio,"February 7, 1940",Pinocchio,Stromboli,When You Wish upon a Star
2,Fantasia,"November 13, 1940",NaN,Chernabog,NaN
3,Dumbo,"October 23, 1941",Dumbo,Ringmaster,Baby Mine
4,Bambi,"August 13, 1942",Bambi,Hunter,Love Is a Song
5,Saludos Amigos,"February 6, 1943",Donald Duck,NaN,Saludos Amigos\n
6,The Three Caballeros,"February 3, 1945",Donald Duck,NaN,NaN
7,Make Mine Music,"April 20, 1946",NaN,NaN,NaN
8,Fun and Fancy Free,"September 27, 1947",Mickey Mouse,Willie the Giant,NaN
9,Melody Time,"May 27, 1948",NaN,NaN,Little Toot
10,The Adventures of Ichabod and Mr. Toad,"October 5, 1949",Mr. Toad and Ichabod Crane,Mr. Winkie and The Headless Horseman,The Merrily Song
11,Cinderella,"February 15, 1950",Cinderella,Lady Tremaine,Bibbidi-Bobbidi-Boo
12,Alice in Wonderland,"July 28, 1951",Alice,Queen of Hearts,The Unbirthday Song
13,Peter Pan,"February 5, 1953",Peter Pan,Captain Hook,You Can Fly!
14,Lady and the Tramp,"June 22, 1955",Lady and Tramp,Si and Am,Bella Notte
15,Sleeping Beauty,"January 29, 1959",Aurora,Maleficent,Once Upon a Dream
16,One Hundred and One Dalmatians,"January 25, 1961",Pongo,Cruella de Vil,Cruella De Vil
17,The Sword in the Stone,"December 25, 1963",Arthur,Madam Mim,Higitus Figitus\n
18,The Jungle Book,"October 18, 1967",Mowgli,Kaa and Shere Khan,The Bare Necessities\n
19,The Aristocats,"December 24, 1970",Thomas and Duchess,Edgar Balthazar,Ev'rybody Wants to Be a Cat
20,Robin Hood,"November 8, 1973",Robin Hood,Prince John,Oo De Lally
21,The Many Adventures of Winnie the Pooh,"March 11, 1977",Winnie the Pooh,NaN,Winnie the Pooh
22,The Rescuers,"June 22, 1977",Bernard and Miss Bianca,Madame Medusa,The Journey
23,The Fox and the Hound,"July 10, 1981",Tod and Copper,Amos Slade,Best of Friends
24,The Black Cauldron,"July 24, 1985",Taran,Horned King,NaN
25,The Great Mouse Detective,"July 2, 1986",Basil,Professor Ratigan,The World's Greatest Criminal Mind
26,Oliver & Company,"November 18, 1988",Oliver,Sykes,Once Upon a Time in New York City
27,The Little Mermaid,"November 17, 1989",Ariel,Ursula,Under the Sea
28,The Rescuers Down Under,"November 16, 1990",Bernard and Miss Bianca,Percival C. McLeach,\n
29,Beauty and the Beast,"November 22, 1991",Belle,Gaston,Be Our Guest
30,Aladdin,"November 25, 1992",Aladdin,Jafar,A Whole New World
31,The Lion King,"June 24, 1994",Simba,Scar,Circle of Life
32,Pocahontas,"June 23, 1995",Pocahontas,Governor Ratcliffe,Colors of the Wind
33,The Hunchback of Notre Dame,"June 21, 1996",Quasimodo,Claude Frollo,God Help the Outcasts
34,Hercules,"June 27, 1997",Hercules,Hades,Go the Distance
35,Mulan,"June 19, 1998",Mulan,Shan Yu,I'll Make a Man Out of You\n
36,Tarzan,"June 18, 1999",Tarzan,Clayton,You'll Be in My Heart
37,Fantasia 2000,"December 17, 1999",NaN,NaN,NaN
38,Dinosaur,"May 19, 2000",Aladar,Kron,NaN
39,The Emperor's New Groove,"December 15, 2000",Kuzco,Yzma,My Funny Friend and Me\n
40,Atlantis: The Lost Empire,"June 15, 2001",Milo Thatch,Commander Rourke,Where the Dream Takes You
41,Lilo & Stitch,"June 21, 2002",Lilo and Stitch,NaN,He Mele No Lilo\n
42,Treasure Planet,"November 27, 2002",Jim Hawkins,John Silver,I'm Still Here\n
43,Brother Bear,"November 1, 2003",Kenai,Denahi,Look Through My Eyes
44,Home on the Range,"April 2, 2004",Maggie,Alameda Slim,NaN
45,Chicken Little,"November 4, 2005",Ace Cluck,Foxy Loxy,NaN
46,Meet the Robinsons,"March 30, 2007",Lewis,Doris,Little Wonders
47,Bolt,"November 21, 2008",Bolt,Dr. Calico,I Thought I Lost You
48,The Princess and the Frog,"December 11, 2009",Tiana,Dr. Facilier,Almost There
49,Tangled,"November 24, 2010",Rapunzel,Mother Gothel,I See the Light
50,Winnie the Pooh,"July 15, 2011",Winnie the Pooh,NaN,Winnie the Pooh\n
51,Wreck-It Ralph,"November 2, 2012",Ralph,Turbo,Sugar Rush
52,Frozen,"November 27, 2013",Elsa,Prince Hans,Let It Go\n
53,Big Hero 6,"November 7, 2014",Hiro Hamada,Professor Callaghan,Immortals
54,Zootopia,"March 4, 2016",Judy Hopps,NaN,Try Everything
55,Moana,"November 23, 2016",Moana,NaN,How Far I'll Go\n

In [13]:
df2 = pd.read_csv("disney_movies_total_gross.csv")
df2

,movie_title,release_date,genre,MPAA_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,"Dec 21, 1937",Musical,G,"$184,925,485","$5,228,953,251"
1,Pinocchio,"Feb 9, 1940",Adventure,G,"$84,300,000","$2,188,229,052"
2,Fantasia,"Nov 13, 1940",Musical,G,"$83,320,000","$2,187,090,808"
3,Song of the South,"Nov 12, 1946",Adventure,G,"$65,000,000","$1,078,510,579"
4,Cinderella,"Feb 15, 1950",Drama,G,"$85,000,000","$920,608,730"
...,...,...,...,...,...,...
574,The Light Between Oceans,"Sep 2, 2016",Drama,PG-13,"$12,545,979","$12,545,979"
575,Queen of Katwe,"Sep 23, 2016",Drama,PG,"$8,874,389","$8,874,389"
576,Doctor Strange,"Nov 4, 2016",Adventure,PG-13,"$232,532,923","$232,532,923"
577,Moana,"Nov 23, 2016",Adventure,PG,"$246,082,029","$246,082,029"
578,Rogue One: A Star Wars Story,"Dec 16, 2016",Adventure,PG-13,"$529,483,936","$529,483,936"

In [14]:
df2["total_gross"]=df2["total_gross"].str.replace("$","")
df2

C:\Users\SHPCTA~1\AppData\Local\Temp/ipykernel_11456/4050910729.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df2["total_gross"]=df2["total_gross"].str.replace("$","")

,movie_title,release_date,genre,MPAA_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,"Dec 21, 1937",Musical,G,"184,925,485","$5,228,953,251"
1,Pinocchio,"Feb 9, 1940",Adventure,G,"84,300,000","$2,188,229,052"
2,Fantasia,"Nov 13, 1940",Musical,G,"83,320,000","$2,187,090,808"
3,Song of the South,"Nov 12, 1946",Adventure,G,"65,000,000","$1,078,510,579"
4,Cinderella,"Feb 15, 1950",Drama,G,"85,000,000","$920,608,730"
...,...,...,...,...,...,...
574,The Light Between Oceans,"Sep 2, 2016",Drama,PG-13,"12,545,979","$12,545,979"
575,Queen of Katwe,"Sep 23, 2016",Drama,PG,"8,874,389","$8,874,389"
576,Doctor Strange,"Nov 4, 2016",Adventure,PG-13,"232,532,923","$232,532,923"
577,Moana,"Nov 23, 2016",Adventure,PG,"246,082,029","$246,082,029"
578,Rogue One: A Star Wars Story,"Dec 16, 2016",Adventure,PG-13,"529,483,936","$529,483,936"

In [15]:
df2["inflation_adjusted_gross"]=df2["inflation_adjusted_gross"].str.replace("$","")
df2

C:\Users\SHPCTA~1\AppData\Local\Temp/ipykernel_11456/1351253998.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df2["inflation_adjusted_gross"]=df2["inflation_adjusted_gross"].str.replace("$","")

,movie_title,release_date,genre,MPAA_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,"Dec 21, 1937",Musical,G,"184,925,485","5,228,953,251"
1,Pinocchio,"Feb 9, 1940",Adventure,G,"84,300,000","2,188,229,052"
2,Fantasia,"Nov 13, 1940",Musical,G,"83,320,000","2,187,090,808"
3,Song of the South,"Nov 12, 1946",Adventure,G,"65,000,000","1,078,510,579"
4,Cinderella,"Feb 15, 1950",Drama,G,"85,000,000","920,608,730"
...,...,...,...,...,...,...
574,The Light Between Oceans,"Sep 2, 2016",Drama,PG-13,"12,545,979","12,545,979"
575,Queen of Katwe,"Sep 23, 2016",Drama,PG,"8,874,389","8,874,389"
576,Doctor Strange,"Nov 4, 2016",Adventure,PG-13,"232,532,923","232,532,923"
577,Moana,"Nov 23, 2016",Adventure,PG,"246,082,029","246,082,029"
578,Rogue One: A Star Wars Story,"Dec 16, 2016",Adventure,PG-13,"529,483,936","529,483,936"

In [17]:

# Import label encoder
from sklearn import preprocessing
  
# label_encoder object knows 
# how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
df2['genre']= label_encoder.fit_transform(df2['genre'])
  
df2['genre'].unique()

array([ 8,  1,  6,  3, 12,  0,  7,  9, 10, 11,  2,  5,  4])

In [18]:
df2

,movie_title,release_date,genre,MPAA_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,"Dec 21, 1937",8,G,"184,925,485","5,228,953,251"
1,Pinocchio,"Feb 9, 1940",1,G,"84,300,000","2,188,229,052"
2,Fantasia,"Nov 13, 1940",8,G,"83,320,000","2,187,090,808"
3,Song of the South,"Nov 12, 1946",1,G,"65,000,000","1,078,510,579"
4,Cinderella,"Feb 15, 1950",6,G,"85,000,000","920,608,730"
...,...,...,...,...,...,...
574,The Light Between Oceans,"Sep 2, 2016",6,PG-13,"12,545,979","12,545,979"
575,Queen of Katwe,"Sep 23, 2016",6,PG,"8,874,389","8,874,389"
576,Doctor Strange,"Nov 4, 2016",1,PG-13,"232,532,923","232,532,923"
577,Moana,"Nov 23, 2016",1,PG,"246,082,029","246,082,029"
578,Rogue One: A Star Wars Story,"Dec 16, 2016",1,PG-13,"529,483,936","529,483,936"